#!/bin/bash
api_SCRIPTROOTDIR=`echo ${BASH_SOURCE[0]} | sed -e 's|\(.*\)/|\1___|' | awk -F "___" '{NF--; print}'`

cd $api_SCRIPTROOTDIR
cd ..
cd ..
cd ..

api_ENVROOTDIR=`pwd`


echo "[environment_variables]:                        setting root directory to [$api_ENVROOTDIR]"







export api_NODEVERSION="node-v16.13.2-linux-x64"
export api_NODEPATH="$api_ENVROOTDIR/lib/bin/linux/node/$api_NODEVERSION"
export api_PATH="$api_ENVROOTDIR/lib/setup/linux:$api_NODEPATH/bin"
export PATH=$api_PATH:$PATH